#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

concourse_pipeline="${1:-2016.changelog.com}"
concourse_url="https://ci.changelog.com"
concourse_target="changelog"

main() {
  configure_pipeline ||
  (
    login
    configure_pipeline
  )
}

login() {
  fly --target "$concourse_target" login \
    --concourse-url "$concourse_url"
}

configure_pipeline() {
  # Some vars defined by .envrc
  fly --target "$concourse_target" set-pipeline \
    --var concourse_ssh_private_key="$CONCOURSE_SSH_PRIVATE_KEY" \
    --var ssh_known_hosts="$SSH_KNOWN_HOSTS" \
    --var dotcom_backup_aws_region="$DOTCOM_BACKUP_AWS_REGION" \
    --var dotcom_backup_s3_bucket="$DOTCOM_BACKUP_S3_BUCKET" \
    --var dotcom_backup_aws_access_key_id="$DOTCOM_BACKUP_AWS_ACCESS_KEY_ID" \
    --var dotcom_backup_aws_secret_access_key="$DOTCOM_BACKUP_AWS_SECRET_ACCESS_KEY" \
    --var postgres_admin_pass="$PG_DOTCOM_PASS" \
    --var campaign_monitor_token="$CM_TOKEN" \
    --config "concourse/${concourse_pipeline}.yml" --pipeline "$concourse_pipeline"
}

main
