#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

ssh_host="2016.changelog.com"
ssh_user="root"

pg_local_port=15432
pg_ip=127.0.0.1
pg_port=5432

pg_user="$(lpass show --username 1394836924033726964)"
pg_pass="$(lpass show --password 1394836924033726964)"

pg_db=changelog
pg_dump_file="$HOME/Downloads/$pg_db.$(date +%Y%m%d.%H%M).sql"

main() {
  install_dependencies
  open_tunnel_to_app_host
  backup_db
}

install_dependencies() {
  brew install postgresql 2>/dev/null
}

open_tunnel_to_app_host() {
  lsof -nPi TCP:$pg_local_port >/dev/null ||
  ssh -NfL $pg_local_port:$pg_ip:$pg_port $ssh_user@$ssh_host
}

backup_db() {
  echo -n "Backing up $pg_db db from $ssh_host to $pg_dump_file ... "

  PGPASSWORD="$pg_pass" pg_dump \
    --host $pg_ip --port $pg_local_port --username "$pg_user" \
    --file "$pg_dump_file" \
    --no-owner --no-privileges \
    $pg_db

  echo "DONE!"
}

main
