#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

pg_dump_file="${1:? first argument must be a valid SQL script file }"
if [ ! -f "$pg_dump_file" ]
then
  echo "$pg_dump_file must be readable and be a valid SQL script file"
  exit 1
fi

read -rp "DB to re-create (defaults to changelog): " pg_db
pg_db="${pg_db:-changelog}"

read -rp "PostgreSQL host: " ssh_host
ssh_host="${ssh_host:?PostgreSQL host must be provided}"
ssh_user="root"
ssh_socket="$ssh_host.sock"

pg_local_port=25432
pg_ip=127.0.0.1
pg_port=5432

pg_user="$(lpass show --username 1394836924033726964)"
pg_pass="$(lpass show --password 1394836924033726964)"

main() {
  install_dependencies
  open_tunnel_to_remote_host
  trap close_tunnel_to_remote_host EXIT
  restore_db
}

install_dependencies() {
  brew install postgresql 2>/dev/null
}

open_tunnel_to_remote_host() {
  ssh -MS "$ssh_socket" -NfL $pg_local_port:$pg_ip:$pg_port "$ssh_user"@"$ssh_host"
}

close_tunnel_to_remote_host() {
  ssh -S "$ssh_socket" -O exit "$ssh_user"@"$ssh_host" 2>/dev/null
}

restore_db() {
  PGPASSWORD="$pg_pass" psql \
    --host $pg_ip --port $pg_local_port --username "$pg_user" \
    "$pg_db" < "$pg_dump_file"

  echo -e "\nOK! $pg_db db on $ssh_host re-created from $pg_dump_file"
}

main
