#!/bin/sh -e

main() {
  set_base_path
  configure_ssh
  play
}

set_base_path() {
  SOURCE="$0"
  DIR="$(dirname "$SOURCE")"
  while [ -h "$SOURCE" ]
  do
    SOURCE="$(readlink "$SOURCE")"
    [ "$SOURCE" != /* ] && SOURCE="${DIR}/$SOURCE"
    DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  done
  BASE_PATH="$(cd "${DIR}/.." && pwd)"
}

configure_ssh() {
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  echo "${SSH_KNOWN_HOSTS:?must be defined}" > ~/.ssh/known_hosts
  echo "${CONCOURSE_SSH_PRIVATE_KEY:?must be defined}" > ~/.ssh/id_rsa
  chmod 600 ~/.ssh/id_rsa
}

play() {
  (
    cd "$BASE_PATH"
    sh -c "ansible-playbook ${ANSIBLE_PLAYBOOK:?must be defined}"
  )
}

main
