#!/bin/sh -e

SSH_KEY_FILE=~/.ssh/id_rsa

main() {
  set_base_path
  setup_ssh
  configure_ssh_client
  configure_ssh_key
  ensure_ssh_key_in_agent
  play
}

set_base_path() {
  SOURCE="$0"
  DIR="$(dirname "$SOURCE")"
  while [ -h "$SOURCE" ]
  do
    SOURCE="$(readlink "$SOURCE")"
    [ "$SOURCE" != /* ] && SOURCE="${DIR}/$SOURCE"
    DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  done
  BASE_PATH="$(cd "${DIR}/.." && pwd)"
}

setup_ssh() {
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh

  echo "${SSH_KNOWN_HOSTS:?must be defined}" > ~/.ssh/known_hosts
}

configure_ssh_client() {
  cat > ~/.ssh/config <<EOF
# Prevent SSH connections timing out (poll the server every 60")
ServerAliveInterval 60
ServerAliveCountMax 3
# Forward local keys remotely
ForwardAgent yes
EOF
}

configure_ssh_key() {

  echo "${CONCOURSE_SSH_PRIVATE_KEY:?must be defined}" > $SSH_KEY_FILE
  chmod 600 $SSH_KEY_FILE

  eval "$(ssh-agent)"
  # shellcheck disable=SC2064
  trap "kill $SSH_AGENT_PID" 0

  ssh-add $SSH_KEY_FILE
}

ensure_ssh_key_in_agent() {
  if ssh-add -l | grep -v "$SSH_KEY_FILE"
  then
    echo "$SSH_KEY_FILE not in SSH AGENT"
    return 1
  fi
}

play() {
  (
    cd "$BASE_PATH"
    sh -c "ansible-playbook ${ANSIBLE_PLAYBOOK:?must be defined}"
  )
}

main
